#!/usr/bin/env bash
#installing and configuring HAProxy for load balancing

sudo apt-get -y update
apt-get -y install haproxy

s_config=\
"
backend isabel-back
        mode http
        balance roundrobin
        server 227247-web-01 100.26.161.155:80 check
        server 227247-web-02 34.227.93.14:80 check
frontend isabel-front
        bind *:80
        mode http
        default_backend isabel-back
"
echo "$s_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
