#!/usr/bin/env bash
#Fixes Nginx so that Nginx is running as the nginx user.

# Configure Nginx to run as the nginx user
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo -u nginx service nginx start
