#!/usr/bin/env bash
#Fixes Nginx so that Nginx is running as the nginx user.

# Configure Nginx to run as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update the Nginx configuration to listen on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

#Change permissions
chmod 644 /etc/nginx/nginx.conf

pkill apache2

# Restart Nginx with new user to apply the changes
sudo -u nginx service nginx start
